import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Logo from "/public/assets/logo.png";
import Script from "next/script";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "안녕하세요. Next App입니다.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //   if (Math.random() < 0.1) throw new Error("RootLayout 오류!");

  return (
    <html lang="en">
      <Script
        dangerouslySetInnerHTML={{
          __html: "window.alert(123)",
        }}
      />
      <body className={`${pretendard.className} antialiased`}>
        <header className="flex h-[60px] w-full items-center justify-center">
          <Image height={40} src={Logo} alt="Logo"></Image>
        </header>
        {children}
      </body>
    </html>
  );
}
